name: Update rbe-erlang-platform
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rbe-images:
    name: Update rbe-erlang-platform
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v4
      with:
        path: rules_erlang
    - name: CHECKOUT rbe-erlang-platform REPOSITORY
      uses: actions/checkout@v4
      with:
        path: rbe-erlang-platform
        repository: rabbitmq/rbe-erlang-platform
        ref: linux-rbe
    - name: DETERMINE LATEST COMMIT
      id: find-commit
      working-directory: rbe-erlang-platform
      run: |
        echo "::set-output name=SHA::$(git rev-parse HEAD)"
    - name: UPDATE rbe-erlang-platform COMMIT
      working-directory: rules_erlang/test
      run: |
        sudo npm install --global --silent @bazel/buildozer
        echo "$(cat WORKSPACE.bazel | npx buildozer 'set commit "${{ steps.find-commit.outputs.SHA }}"' -:rbe)" > WORKSPACE.bazel
        git diff
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v6.0.2
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        title: Adopt latest rabbitmq-server-buildenv:linux-rbe for RBE
        path: rules_erlang
        commit-message: |
          Use latest rbe-erlang-platform/linux-rbe

          for remote build execution (RBE) with BuildBuddy
        branch: bump-rbe
        delete-branch: true
